regions: ["NIGERIA"]
start_year: 2018
n_days: 2190
pop_scale: 1
vx_prob_ri: 0.0
init_region: "BIRINIWA"
init_prev: 0
seed_schedule:
  - date: "2018-01-02"
    dot_name: "AFRO:NIGERIA:JIGAWA:HADEJIA"
    prevalence: 100
  - date: "2018-01-02"
    dot_name: "AFRO:NIGERIA:JIGAWA:GARKI"
    prevalence: 100
  - date: "2020-07-01"
    dot_name: "AFRO:NIGERIA:ZAMFARA:TALATA_MAFARA"
    prevalence: 100
  - date: "2020-10-01"
    dot_name: "AFRO:NIGERIA:NIGER:SULEJA"
    prevalence: 100
migration_method: "gravity"
max_migr_frac: 1.0
results_path: "results/demo_nigeria"
save_plots: false
save_data: true
summary_config:
  region_groups:
    northern_nigeria:
      - "NIGERIA:ADAMAWA"
      - "NIGERIA:BAUCHI"
      - "NIGERIA:BENUE"
      - "NIGERIA:BORNO"
      - "NIGERIA:FCT"
      - "NIGERIA:GOMBE"
      - "NIGERIA:JIGAWA"
      - "NIGERIA:KADUNA"
      - "NIGERIA:KANO"
      - "NIGERIA:KATSINA"
      - "NIGERIA:KEBBI"
      - "NIGERIA:KOGI"
      - "NIGERIA:KWARA"
      - "NIGERIA:NASARAWA"
      - "NIGERIA:NIGER"
      - "NIGERIA:PLATEAU"
      - "NIGERIA:SOKOTO"
      - "NIGERIA:TARABA"
      - "NIGERIA:YOBE"
      - "NIGERIA:ZAMFARA"
    southern_nigeria:
      - "NIGERIA:ABIA"
      - "NIGERIA:ADAMAWA"
      - "NIGERIA:AKWA_IBOM"
      - "NIGERIA:ANAMBRA"
      - "NIGERIA:BAYELSA"
      - "NIGERIA:CROSS_RIVER"
      - "NIGERIA:DELTA"
      - "NIGERIA:EBONYI"
      - "NIGERIA:EDO"
      - "NIGERIA:EKITI"
      - "NIGERIA:ENUGU"
      - "NIGERIA:IMO"
      - "NIGERIA:LAGOS"
      - "NIGERIA:OGUN"
      - "NIGERIA:ONDO"
      - "NIGERIA:OSUN"
      - "NIGERIA:OYO"
      - "NIGERIA:RIVERS"
use_pim_scalars: false
node_seeding_dispersion: 1.0
