regions: [
    "BENIN",
    "BURKINA_FASO",
    "COTE_DIVOIRE",
    "GAMBIA",
    "GHANA",
    "GUINEA",
    "GUINEA_BISSAU",
    "LIBERIA",
    "MALI",
    "MAURITANIA",
    "NIGER",
    "NIGERIA",
    "SENEGAL",
    "SIERRA_LEONE",
    "TOGO",
]
admin_level: 0
start_year: 2017
n_days: 2555
pop_scale: 1
vx_prob_ri: 0.0
init_region: "BIRINIWA"
init_prev: 0
seed_schedule:
  - date: "2017-10-01"
    dot_name: "AFRO:NIGERIA:JIGAWA:HADEJIA"
    prevalence: 100
  - date: "2017-10-01"
    dot_name: "AFRO:NIGERIA:JIGAWA:GARKI"
    prevalence: 100
  - date: "2020-07-01"
    dot_name: "AFRO:NIGERIA:ZAMFARA:TALATA_MAFARA"
    prevalence: 100
  - date: "2020-10-01"
    dot_name: "AFRO:NIGERIA:NIGER:SULEJA"
    prevalence: 100
migration_method: "gravity"
node_seeding_dispersion: 1.0
use_pim_scalars: false
results_path: "results/demo_nigeria"
save_plots: false
save_data: true
summary_config:
  time_periods:
    bins: ["2020-07-01", "2022-07-01"]  # Split points
    labels: ["2017-2020.5", "2020.5-2022.5", "2022.5-2024"]
  region_groups:
    north_central:
      - "NIGERIA:BENUE"
      - "NIGERIA:FCT"
      - "NIGERIA:KOGI"
      - "NIGERIA:KWARA"
      - "NIGERIA:NASARAWA"
      - "NIGERIA:NIGER"
      - "NIGERIA:PLATEAU"
    north_east:
      - "NIGERIA:ADAMAWA"
      - "NIGERIA:BAUCHI"
      - "NIGERIA:BORNO"
      - "NIGERIA:GOMBE"
      - "NIGERIA:TARABA"
      - "NIGERIA:YOBE"
    north_west:
      - "NIGERIA:JIGAWA"
      - "NIGERIA:KADUNA"
      - "NIGERIA:KANO"
      - "NIGERIA:KATSINA"
      - "NIGERIA:KEBBI"
      - "NIGERIA:SOKOTO"
      - "NIGERIA:ZAMFARA"
    southern:
      - "NIGERIA:ABIA"
      - "NIGERIA:ANAMBRA"
      - "NIGERIA:AKWA_IBOM"
      - "NIGERIA:BAYELSA"
      - "NIGERIA:CROSS_RIVER"
      - "NIGERIA:DELTA"
      - "NIGERIA:EBONYI"
      - "NIGERIA:EDO"
      - "NIGERIA:EKITI"
      - "NIGERIA:ENUGU"
      - "NIGERIA:IMO"
      - "NIGERIA:LAGOS"
      - "NIGERIA:OGUN"
      - "NIGERIA:ONDO"
      - "NIGERIA:OSUN"
      - "NIGERIA:OYO"
      - "NIGERIA:RIVERS"
