regions: [
    "BENIN",
    "GAMBIA",
    "GUINEA_BISSAU",
    "LIBERIA",
    "MAURITANIA",
    "SIERRA_LEONE",
    "TOGO",
]
admin_level: 0
start_year: 2017
n_days: 2555
pop_scale: 1.0
vx_prob_ri: 0.0
init_region: "ZOU:ABOMEY"
init_prev: 200
migration_method: "gravity"
max_migr_frac: 0.1
node_seeding_dispersion: 1.0
use_pim_scalars: false
results_path: "results/demo_nigeria"
save_plots: false
save_data: true
summary_config:
  time_periods:
    bins: ["2020-07-01", "2022-07-01"]  # Split points
    labels: ["2017-2020.5", "2020.5-2022.5", "2022.5-2024"]
