regions: ["ZAMFARA"]
start_year: 2018
n_days: 2190
pop_scale: 1
vx_prob_ri: null
init_region: "ANKA"
init_prev: 0
seed_schedule:
  - date: "2018-02-06"
    dot_name: "AFRO:NIGERIA:ZAMFARA:ANKA"
    prevalence: 200
  - date: "2020-11-24"
    dot_name: "AFRO:NIGERIA:ZAMFARA:SHINKAFI"
    prevalence: 200
migration_method: "radiation"
results_path: "results/demo_zamfara"
init_pop_file: "data/init_pop_zamfara_6y.h5"
save_plots: false
save_data: true
summary_config:
  region_groups:
    northern_nigeria: [0, 1, 2]
    southern_nigeria: [3, 4, 5]
    major_hubs: [0, 5]
