---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "superSecretPassword"
  MYSQL_USER: "optuna"
  MYSQL_PASSWORD: "superSecretPassword"
  MYSQL_DB: "optunaDatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk-claim
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /var/lib/mysql
              name: mysql-storage
              subPath: mysql
          envFrom:
            - secretRef:
                name: mysql-secrets
          ports:
            - containerPort: 3306
     
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exposed
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: LoadBalancer
---